---
title: "Data Preprocessing"
output: html_notebook
---

## Importing libraries

```{r}
library(caTools)
```

## Importing the dataset

```{r}
data <- read.csv(file = "A://Machine-Learning-A-Z/data/Data.csv")
```

```{r}
View(data)
```

## Taking care of missing values

```{r}
# Is there any missing values
colSums(is.na(data))
```

```{r}
# Age

data$Age <- ifelse(test = is.na(data$Age),
                   yes = ave(x = data$Age, FUN = function(x) mean(x, na.rm = T)),
                   no = data$Age)
```

```{r}
# Salary

data$Salary <- ifelse(test = is.na(data$Salary),
                   yes = ave(x = data$Salary, FUN = function(x) mean(x, na.rm = T)),
                   no = data$Salary)
```

```{r}
# Let's check if there are any missing values left
colSums(is.na(data))
```

## Encoding categorical variable

```{r}
# Country

data$Country <- factor(x = data$Country, 
                       levels = c("France", "Spain", "Germany"),
                       labels = c(1, 2, 3))
```

```{r}
# Purchased

data$Purchased <- factor(x = data$Purchased, 
                       levels = c("Yes", "No"),
                       labels = c(1, 0))
```

## Splitting the dataset into training set and test set

```{r}
set.seed(seed = 123)
split <- sample.split(Y = data$Purchased, SplitRatio = 0.8)
split
```

```{r}
training_set <- subset(x = data, split == T)
test_set <- subset(x = data, split == F)
```

## Feature scaling

```{r}
training_set[, 2:3] <- scale(training_set[, 2:3])
test_set[, 2:3] <- scale(test_set[, 2:3])
```

